export const themes = {
    minimalist: {
        name: 'Minimalist',
        description: 'Simple and clean',
        fontFamily: 'serif',
        fontSize: 'base',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textColor: '#2d3748',
        titleColor: '#1a202c',
        backgroundColor: '#ffffff',
        boardBackgroundColor: '#ffffff',
        boardPattern: 'grid',
        boardPatternColor: '#e2e8f0',
        boardPatternColor2: '#cbd5e0',
        titleBackgroundColor: 'transparent',
        borderColor: '#cbd5e0',
        borderWidth: '1',
        borderStyle: 'solid',
        cornerStyle: 'square',
        stampStyle: 'none',
        stampImage: null,
        stampSize: 'medium',
        stampOpacity: 0.4,
        stampRandomize: false,
        stampCells: [],
        centerStyle: 'text',
        centerImage: null,
        title: 'bingo.',
        titleSize: 'medium',
    },
    vintage: {
        name: 'Vintage',
        description: 'Classic dinner style red',
        fontFamily: 'bespokeserif',
        fontSize: 'base',
        fontWeight: '800',
        fontStyle: 'italic',
        textColor: '#fa3a00',
        titleColor: '#fa3a00',
        backgroundColor: '#fffcfa',
        boardBackgroundColor: '#f9f0f0',
        boardPattern: 'checkerboard',
        boardPatternColor: '#ffffff',
        boardPatternColor2: '#cbd5e0',
        titleBackgroundColor: 'transparent',
        borderColor: '#fa3a00',
        borderWidth: '5',
        borderStyle: 'double',
        cornerStyle: 'very-rounded',
        stampStyle: 'none',
        stampImage: null,
        stampSize: 'medium',
        stampOpacity: 0.4,
        stampRandomize: false,
        stampCells: [],
        centerStyle: 'text',
        centerImage: null,
        title: '◇ BINGO◇',
        titleSize: 'xxlarge',
    },
    elegant: {
        name: 'Elegant',
        description: 'Sophisticated black and gold',
        fontFamily: 'stardom',
        fontSize: 'normal',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textColor: '#1a1a1a',
        titleColor: '#d4af37',
        backgroundColor: '#fafafa',
        boardBackgroundColor: '#ffffff',
        boardPattern: 'gradient',
        boardPatternColor: '#fafafa',
        boardPatternColor2: '#fff8e1',
        titleBackgroundColor: '#1a1a1a',
        borderColor: '#d4af37',
        borderWidth: '2',
        borderStyle: 'double',
        cornerStyle: 'square',
        stampStyle: 'none',
        stampImage: null,
        stampSize: 'medium',
        stampOpacity: 0.4,
        stampRandomize: false,
        stampCells: [],
        centerStyle: 'star',
        centerImage: null,
        title: 'BINGO',
        titleSize: 'xxlarge',
    },
    playful: {
        name: 'Playful',
        description: 'Bright and fun',
        fontFamily: 'nunito',
        fontSize: 'base',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textColor: '#ff0066',
        titleColor: '#ffffff',
        backgroundColor: '#f8f1f1',
        boardBackgroundColor: '#ff932e',
        boardPattern: 'gradient',
        boardPatternColor: '#ff932e',
        boardPatternColor2: '#c800ff',
        titleBackgroundColor: '#1a1a1a',
        borderColor: '#bb00ff',
        borderWidth: '3',
        borderStyle: 'dotted',
        cornerStyle: 'very-rounded',
        stampStyle: 'none',
        stampImage: null,
        stampSize: 'medium',
        stampOpacity: 0.4,
        stampRandomize: false,
        stampCells: [],
        centerStyle: 'heart',
        centerImage: null,
        title: 'bingo !',
        titleSize: 'xxlarge',
    },
    futuristic: {
        name: 'Spacescape',
        description: 'dark and clean',
        fontFamily: 'array',
        fontSize: 'base',
        fontWeight: 'normal',
        fontStyle: 'normal',
        textColor: '#2d3748',
        titleColor: '#ffffff',
        backgroundColor: '#ffffff',
        boardBackgroundColor: '#000000',
        boardPattern: 'gradient',
        boardPatternColor: '#000000',
        boardPatternColor2: '#042f5d',
        titleBackgroundColor: 'transparent',
        borderColor: '#cbd5e0',
        borderWidth: '3',
        borderStyle: 'solid',
        cornerStyle: 'square',
        stampStyle: 'none',
        stampImage: null,
        stampSize: 'medium',
        stampOpacity: 0.4,
        stampRandomize: false,
        stampCells: [],
        centerStyle: 'star',
        centerImage: null,
        title: 'b . I . n . G . o .',
        titleSize: 'medium',
    },
}

export const getTheme = (themeName) => {
    return themes[themeName] || themes.default
}

export const getThemeNames = () => {
    return Object.keys(themes)
}

